version: 3.7

services:
  
  zf:
    build: .
    dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
    links:
      - mysql
    environment: 
      DB_HOST: mysql
      DB_DATABASE: angularjs-zend-todo
      DB_USERNAME: root
      DB_PASSWORD: root

  mysql:
    image: mysql:5.7
    ports:
      - 13306:3306
    environment: 
      MYSQL_DATABASE: angularjs-zend-todo
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
