<?= $this->doctype() ?>

<html lang="en" ng-app="Todo">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('angularjs-zend-todo')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])?>

    </head>
    <body>
        <div class="container">
            <?= $this->content ?>
        </div>

        <script src="js/main.bundle.js"></script>
    </body>
</html>
